"""phase_a_grok_daily_cost_pk

Revision ID: 0006_phase_a_grok_daily_cost_pk
Revises: 0005_phase_a_fan_columns
Create Date: 2026-05-22

Hand-written (NOT autogenerated). Reshapes the grok_daily_cost PK from
`day` only → `(day, account_id)` so the soft-cap enforcement can roll up
spend per-account. account_id is nullable + part of the PK so a global
rollup row (account_id=NULL) can coexist with per-account rows on the
same day (SQLite treats NULL as distinct in composite PKs).

Why hand-written: SQLite cannot ALTER PRIMARY KEY. The autogenerate
proposal in 0005 just added the column + FK without touching the PK,
which leaves the table in a broken half-migrated shape. We rebuild the
table via create-new + copy + swap (the pattern from
library/db_data/06_gaps_and_migrations.md §3).

Existing rows get account_id=NULL, preserving them as the global rollup.
Wrapped in a single transaction so a failed copy doesn't leave the DB
half-swapped.

Downgrade caveat: collapsing the new composite PK back to `day`-only
requires aggregating across account_ids. We SUM cost_cents + call_count,
take MAX(is_capped) and MAX(updated_at), GROUP BY day. Per-account
granularity is lost on downgrade — irreversible by design.
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0006_phase_a_grok_daily_cost_pk"
down_revision: str | Sequence[str] | None = "0005_phase_a_fan_columns"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Alembic begins a transaction around this function; SQLite supports
    # transactional DDL for CREATE/INSERT/DROP/RENAME, so a failure mid-way
    # rolls everything back.
    op.execute(sa.text(
        """
        CREATE TABLE grok_daily_cost_new (
            day VARCHAR NOT NULL,
            account_id VARCHAR,
            cost_cents INTEGER NOT NULL,
            call_count INTEGER NOT NULL,
            is_capped BOOLEAN NOT NULL,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_grok_daily_cost PRIMARY KEY (day, account_id),
            CONSTRAINT fk_grok_daily_cost_account_id_accounts
                FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE
        )
        """
    ))
    op.execute(sa.text(
        """
        INSERT INTO grok_daily_cost_new
            (day, account_id, cost_cents, call_count, is_capped, updated_at)
        SELECT day, NULL, cost_cents, call_count, is_capped, updated_at
          FROM grok_daily_cost
        """
    ))
    op.execute(sa.text("DROP TABLE grok_daily_cost"))
    op.execute(sa.text("ALTER TABLE grok_daily_cost_new RENAME TO grok_daily_cost"))


def downgrade() -> None:
    # Rebuild the old single-column-PK shape. Aggregate cost across all
    # account_ids for each day so the rollup totals survive even though
    # the per-account split is lost.
    op.execute(sa.text(
        """
        CREATE TABLE grok_daily_cost_old (
            day VARCHAR NOT NULL,
            cost_cents INTEGER NOT NULL,
            call_count INTEGER NOT NULL,
            is_capped BOOLEAN NOT NULL,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT pk_grok_daily_cost PRIMARY KEY (day)
        )
        """
    ))
    op.execute(sa.text(
        """
        INSERT INTO grok_daily_cost_old
            (day, cost_cents, call_count, is_capped, updated_at)
        SELECT day,
               SUM(cost_cents),
               SUM(call_count),
               MAX(is_capped),
               MAX(updated_at)
          FROM grok_daily_cost
         GROUP BY day
        """
    ))
    op.execute(sa.text("DROP TABLE grok_daily_cost"))
    op.execute(sa.text("ALTER TABLE grok_daily_cost_old RENAME TO grok_daily_cost"))
